### ISSUE TITLE
Viewer does not respect scheduled presentations.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/schedules-app#45]
Steps to reproduce:
1. Schedule four presentations
2. Set two presentations to run only in a certain timeframe (10:00PM - 10:15PM Daily)
3. Set two presentations to run always
4. Assign to display

Result:
All four presentations will run regardless of time.

How it should work:
Presentations schedule for a certain timeframe should only appear during that timeframe

Link to schedule:
https://schedules.risevision.com/#/schedule/details/dea1ee97-2a6d-4f8a-9cc7-9793ef61f6fd?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

OS:
All

Chrome Ver:
44.*

**Comment by alex-deaconu** [comment]
@btfrise to confirm, this behaviour works correctly if Schedules via the RVA. It only occurs in the Schedules App? Thanks.

**Comment by alex-deaconu** [comment]
@btfrise also, can you provide a version of a Schedule where we can replicate this? Thanks.

**Comment by btfrise** [comment]
@alex-deaconu that is correct. I've added the schedule link to the original post.

**Comment by alex-deaconu** [comment]
@btfrise awesome, thanks!

**Comment by alex-deaconu** [comment]
@btfrise this issue is now fixed. Please verify & close. Thanks.

**Comment by alex-deaconu** [comment]
@btfrise what is the status of this issue? Thanks.

**Comment by ByronDarlison** [comment]
@btfrise @alex-deaconu can you confirm if this is closed? Thanks

**Comment by alex-deaconu** [comment]
@ByronDarlison I fixed this a while back, so it should be working fine. @btfrise can you confirm? Thanks.

**Comment by ByronDarlison** [comment]
@btfrise can you confirm this is fixed.

**Comment by btfrise** [comment]
@alex-deaconu @ByronDarlison Confirmed fixed.
